name: Deploy MarktPandaBot

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.26.0"
          cache: true

      - name: Install Go Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v -race ./...

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Build Static Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o marktpanda_bot main.go

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Copy Binary to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "marktpanda_bot"
          target: "/tmp/"

      - name: Finalize Deployment and Restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/marktpandabot

            sudo mv /tmp/marktpanda_bot /opt/marktpandabot/marktpanda_bot

            echo "${{ secrets.ENV_FILE }}" | sudo tee /opt/marktpandabot/.env > /dev/null

            sudo chown -R ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_USER }} /opt/marktpandabot

            sudo chmod 400 /opt/marktpandabot/.env
            sudo chmod 500 /opt/marktpandabot/marktpanda_bot

            sudo systemctl restart marktpandabot
